language: android
dist: trusty
env:
  global:
    - TERM=dumb
    - ANDROID_TARGET=android-16
    - ANDROID_ABI=armeabi-v7a

android:
  components:
    - build-tools-25.0.2
    - $ANDROID_TARGET
    - sys-img-armeabi-v7a-android-16


before_script:
  - android list targets
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &


script: 
  - cd client
  - ./gradlew build connectedAndroidTest