name: Android UI Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  UITest:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8      
    - name: Run UI Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 16
        script: ./gradlew connectedAndroidTest
        working-directory: ./client
