name: Android CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, dev]

jobs:
  UITest:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run UI Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 24
          disable-animations: true
          script: ./gradlew connectedAndroidTest --full-stacktrace
          working-directory: ./client
          emulator-options: -no-window

  UnitTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run Tests
        run: ./gradlew build test
        working-directory: client
      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }} # IMPORTANT: run Android Test Report regardless
